project_name: nfetch
before:
  hooks:
    - go mod tidy
    - go generate ./...
    - ./scripts/update_bash_completions.sh
builds:
  - id: nix
    env:
      - CGO_ENABLED=0
      - GO386=softfloat
    goos:
      - linux
      # - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
    main: ./nfetch

  - id: windows
    env:
      - CGO_ENABLED=0
      - GO386=softfloat
    goos:
      - windows
    goarch:
      - 386
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w
    main: ./nfetch

archives:
  - id: windows
    builds:
      - windows
    format: zip
    files:
      - completions/nfetch.ps1
    replacements:
      386: x86
      amd64: x64

  - id: nix
    builds:
      - nix
    files:
      - completions/nfetch.zsh
      - completions/nfetch.fish
      - completions/nfetch.sh

nfpms:
  - license: MIT
    maintainer: Joshua Cowie-Willox <joshwillox@gmail.com>
    homepage: https://github.com/jcwillox/nfetch
    description: "A modern neofetch alternative"
    bindir: /usr/bin
    formats:
      - apk
      - rpm
      - deb
    contents:
      - src: completions/nfetch.zsh
        dst: /usr/share/zsh/vendor-completions/_nfetch
      - src: completions/nfetch.fish
        dst: /usr/share/fish/vendor_completions.d/nfetch.fish
      - src: completions/nfetch.sh
        dst: /etc/bash_completion.d/nfetch

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  draft: true