before:
  hooks:
    - go mod tidy

snapshot:
  name_template: "{{ .Version }}"

checksum:
  name_template: 'checksums.txt'

builds:
  - id: nix
    env:
      - CGO_ENABLED=0
      - GO386=softfloat
    goos:
      - linux
      # - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
    main: ./nfetch

  - id: windows
    env:
      - CGO_ENABLED=0
      - GO386=softfloat
    goos:
      - windows
    goarch:
      - "386"
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w
    main: ./nfetch

archives:
  - id: windows
    builds:
      - windows
    format: zip
    files:
      - completions/nfetch.ps1
    replacements:
      386: x86
      amd64: x64

  - id: nix
    builds:
      - nix
    files:
      - completions/nfetch.zsh
      - completions/nfetch.fish
      - completions/nfetch.bash
    replacements:
      386: i386
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

nfpms:
  - file_name_template: '{{ .PackageName }}_{{ .Version }}_{{ .Arch }}'
    replacements:
      386:
        i386
    license: MIT
    maintainer: Joshua Cowie-Willox <joshwillox@gmail.com>
    homepage: https://github.com/jcwillox/nfetch
    description: "A modern neofetch alternative"
    bindir: /usr/bin
    formats:
      - apk
      - rpm
      - deb
    contents:
      - src: completions/nfetch.zsh
        dst: /usr/share/zsh/vendor-completions/_nfetch
      - src: completions/nfetch.fish
        dst: /usr/share/fish/vendor_completions.d/nfetch.fish
      - src: completions/nfetch.bash
        dst: /etc/bash_completion.d/nfetch
