lines:
  - title
  - dashes
  - os
  - host
  - kernel
  - motherboard
  - uptime
  - pkgs
  - shell
  - resolution
  - terminal
  # - theme
  - cpu
  - gpu
  # - cpu_usage
  - memory
  # - swap
  - disk
  # - battery
  # - locale
  # - weather
  # - local_ip
  # - public_ip
  - blank
  - colorbar
